### ISSUE TITLE
Admin can't change user's information

### ISSUE THREAD

**Issue by AlekseyDob** [test-storage/test-storage#54]
## I'm submitting a...

<pre><code>
[х] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
Admin can't change user's information into "fa-user" link.

## Expected behavior
Admin can change the information in user's profile.

## STEPS TO REPRODUCE
1. Open the app
2. Input login and password
3. Open "fa-user" link
4. Verify changing user's information

## Environment
Windows 8.1, Сhrome 57.0.2987.110
![screenshot_1](https://user-images.githubusercontent.com/30245459/28423665-5af55c42-6d74-11e7-9aaa-1d68e25654f2.png)

**Comment by pumano** [comment]
fixed
