### ISSUE TITLE
multiple notification (delete)

### ISSUE THREAD

**Issue by Vurybalo** [test-storage/test-storage#61]
## I'm submitting a...

<pre><code>
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

If you click on the delete button n times will come n notifications

## Expected behavior

When you click on the delete button 1 time or more, only 1 notification should come

## Minimal reproduction of the problem with instructions

1) login app
2) Сlick the button "projects"
3) On the selected project click button "view"
4) Quickly and repeatedly click the button "delete"

## What is the motivation / use case for changing the behavior?

improving usability
![bug_of_delete](https://user-images.githubusercontent.com/30802131/29121026-8689bf6e-7d15-11e7-8d49-8111888dc8ba.gif)

## Environment

windows 7, chrome v. 60.0.3112.90

**Comment by pumano** [comment]
Fixed in 6760a37f878782499d215a2f1d33f6922e19d49e
