### ISSUE TITLE
The inscription and the button overlap each other

### ISSUE THREAD

**Issue by Vurybalo** [test-storage/test-storage#64]
## I'm submitting a...

<pre><code>
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

The inscription and the button overlap each other
Overlap partially depends on the main menu, if you expand the menu, the overlap will be larger

## Expected behavior

The inscription and the button are located correctly and not overlap each other

## Minimal reproduction of the problem with instructions

1) login app
2) click "Project"
3) click "View"
4) If the main menu is minimized, expand it

## What is the motivation / use case for changing the behavior?

improving usability
## Environment

windows 7, chrome v. 60.0.3112.90, opera v.41.0.2353.69
![image](https://user-images.githubusercontent.com/30802131/29173944-802c5ca2-7ded-11e7-8540-e7d53e1ff4fb.jpg)
![image](https://user-images.githubusercontent.com/30802131/29173947-807b8386-7ded-11e7-8a0c-0a1cf31ce876.jpg)

**Comment by pumano** [comment]
Fixed
