### ISSUE TITLE
change display of the projects

### ISSUE THREAD

**Issue by Vurybalo** [test-storage/test-storage#68]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[Х] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

page "projects"
In the first line there are only two projects
And a lot of free space

## Expected behavior

Page"projects"
In the first line there are three projects 

## Minimal reproduction of the problem with instructions

1) login app
2) click "projects"

## What is the motivation / use case for changing the behavior?

improving usability

## Environment

windows 7, chrome v. 60.0.3112.90 Opera v. 41.0.2353.69
![image](https://user-images.githubusercontent.com/30802131/29212215-f4e8e07a-7ea5-11e7-919c-18a409be1943.jpg)

**Comment by pumano** [comment]
fixed
