### ISSUE TITLE
all users have the same email and phone number in "user profile "

### ISSUE THREAD

**Issue by Vurybalo** [test-storage/test-storage#70]
## I'm submitting a...

<pre><code>
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

all users have the same email and phone number in "user profile"

## Expected behavior

Every user have own email and phone number in "user profile"

## Minimal reproduction of the problem with instructions

1) create new user
When creating, enter a unique phone number and email
2) chack this in profile

## What is the motivation / use case for changing the behavior?

improving usability
![image](https://user-images.githubusercontent.com/30802131/29241329-00eac232-7f80-11e7-9a97-0be7bf059843.jpg)
![image](https://user-images.githubusercontent.com/30802131/29241348-533a2686-7f80-11e7-90dd-62f116dd45c9.jpg)

## Environment

windows 7, chrome v. 60.0.3112.90 Opera v. 41.0.2353.69

**Comment by pumano** [comment]
fixed
