### ISSUE TITLE
successful creation of a new user, without password confirmation

### ISSUE THREAD

**Issue by Vurybalo** [test-storage/test-storage#77]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

When creating a new user, the password confirmation field can be left blank and you can successfully create the user

## Expected behavior

to successfully create a new user, the "repeat password" field must be correctly filled in

## Minimal reproduction of the problem with instructions

1. Login
2. click the "Users" button
3. click the "create new user" button
4. fill in all the fields except "Confirm Password"
5. click the "create user" button
## Environment

windows 7, chrome v. 61.0.3163.100

**Comment by pumano** [comment]
Fixed
