### ISSUE TITLE
ERROR in : Can't bind to 'clDgRowSelection' since it isn't a known property of 'clr-datagrid'.

### ISSUE THREAD

**Issue by 87abhii** [test-storage/test-storage#92]
ERROR in : Can't bind to 'clDgRowSelection' since it isn't a known property of 'clr-datagrid'.
1. If 'clr-datagrid' is an Angular component and it has 'clDgRowSelection' input, then verify that it is part of this module.
2. If 'clr-datagrid' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("

        <clr-datagrid *ngIf="users" [(clrDgSelected)]="selectedUsers" [ERROR ->][clDgRowSelection]="true">
          <clr-dg-action-bar>
            <div class="btn-group">
")

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test-storage@0.40.0 build: `ng build --prod && tsc -p ./server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the test-storage@0.40.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-02-06T23_02_54_726Z-debug.log

**Comment by pumano** [comment]
Thanks for issue! I'm too busy, but I found some time to fix it. Closes via #93

**Comment by pumano** [comment]
Fixed
